### PR TITLE
docs: fix rendering of warning in README.md

### PR DESCRIPTION
**Pull request by dsanders11**
It looks like the GitHub alert syntax doesn't render correctly if nested into a list (probably something GitHub should fix/support). To fix in this repo, remove the indentation and then ensure the list continues from the correct number (it's technically two different lists now that there's a block between them).

### CODE REVIEW

**Comment by ncalteen** [comment]
👋🏻 @dsanders11 Thanks for the pull request! That's strange, especially since it renders locally without issue (using [this plugin](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles).

Only issue I see is that this causes the numbered list to restart at `1` after the warning. Could you adjust this to just remove the warning syntax and leave it as an additional paragraph below the step?

**Comment by dsanders11** [comment]
> Only issue I see is that this causes the numbered list to restart at 1 after the warning.

Hmm, is that when it renders locally? On GitHub it renders correctly (I set the number after the warning so the list starts at the correct number), see the preview. Might be a case of the local render and the GitHub render both being slightly different in various ways. 🙂

> Could you adjust this to just remove the warning syntax and leave it as an additional paragraph below the step?

I can make this change, just curious to hear the above answer before I do.

**Comment by ncalteen** [comment]
Ah yes you're right! Apparently this is the case of local issues on my part. Updating the review shortly and thank you for the sanity check :)

**Review by ncalteen — COMMENTED** [review]
Can you just run `npm format:write` to make sure the file is formatted correctly?

**Comment by dsanders11** [comment]
Done - looks like it wanted to rewrap the lines after the indentation decreased for the block.

**Comment by dsanders11** [comment]
Looks like the linter didn't like manually setting the list number to fix the rendering. 😞 I've updated the state to your earlier ask about removing the `[!WARNING]` syntax and leaving the block indented.

**Review by ncalteen — APPROVED** [review]

**Pull request merged**
